

export const TOOLS = {
    SEARCH_SHOP_CATALOG: "search_shop_catalog",
    SEARCH_SHOP_CATALOG_DESCRIPTION: "Retrieve and search storefront product listings from the Shopify MCP server. This includes querying the remote storefront URL to return product details such as titles, descriptions, pricing, and availability.",

    SHOP_POLICIES: "search_shop_policies_and_faqs",
    SHOP_POLICIES_DESCRIPTION: "Access shop policies and FAQs stored in the Shopify MCP server. Includes details on returns, refunds, shipping, payments, warranties, and customer support.",

    GET_CART: "get_cart",
    GET_CART_DESCRIPTION: "Fetch the current shopping cart details for the user from the Shopify MCP server. Returns items, quantities, pricing, discounts, taxes, and totals.",

    UPDATE_CART: "update_cart",
    UPDATE_CART_DESCRIPTION: "Modifies or updates/adds the user's shopping cart on the Shopify MCP server by adding, updating, or removing line items, adjusting quantities, applying or removing discounts, and recalculating the cart's totals, including taxes and shipping, to ensure accurate order details.",

    ADD_NUMBERS: "addTwoNumbers",
    ADD_NUMBERS_DESCRIPTION: "Utility function to add two numbers. Primarily used for testing or demonstration purposes within the Account Editor server.",

    ORDER_DETAILS: "get_order_details_ae",
    ORDER_DETAILS_DESCRIPTION: "Retrieve complete order details from the Account Editor server, including product information, customer details, payment status, and shipping information.",

    ADD_PRODUCT: "add_product_order_ae",
    ADD_PRODUCT_DESCRIPTION: "Add new products to an existing order in the Account Editor server. Useful for order modifications and upselling scenarios.",

    REMOVE_PRODUCT: "remove_product_order_ae",
    REMOVE_PRODUCT_DESCRIPTION: "Remove products from an existing order in the Account Editor server. Ensures that order totals and inventory are updated accordingly.",

    EDIT_PRODUCT: "edit_quantity_order_ae",
    EDIT_PRODUCT_DESCRIPTION: "Modify the quantity of products within an existing order in the Account Editor server. Automatically recalculates pricing and totals.",

    EDIT_ADDRESS: "edit_address_order_ae",
    EDIT_ADDRESS_DESCRIPTION: "Update or replace the shipping/billing address for an existing order in the Account Editor server.",

    APPLY_DISCOUNT: "apply_discount_ae",
    APPLY_DISCOUNT_DESCRIPTION: "Apply a discount code or custom discount to an existing order in the Account Editor server. Adjusts order totals and recalculates taxes.",

    CANCEL_ORDER: "cancel_order_ae",
    CANCEL_ORDER_DESCRIPTION: "Cancel an existing order through the Account Editor server. Updates order status and triggers refund or inventory adjustments where applicable.",

    ORDER_LIST: "orders_list_ae",
    ORDER_LIST_DESCRIPTION: "Retrieve a list of all customer orders from the Account Editor server. Includes order IDs, statuses, dates, and key summary details.",

    ACCEPT_REFUND: "accept_refund_ae",
    ACCEPT_REFUND_DESCRIPTION: "Process and accept a refund request for an order in the Account Editor server. Updates order and payment records accordingly.",

    STORE_FRONT_DATABASE: "storefront_database_ae",
    STORE_FRONT_DATABASE_DESCRIPTION: "Access the storefront analytics database within the Account Editor server. Provides data on order edits, revenue impact, and other metrics via RAG retrieval.",

    INSIGHTS: "insights_ae",
    INSIGHTS_DESCRIPTION: "Provide customer and business insights generated by the Account Editor server. This tool should be called daily to display analytics, trends, and personalized recommendations.",

}